export const scorecard = {
  meta: {
    matchTypeId: 6,
    series: {
      id: 2141,
      name: "IPL 2018",
    },
  },
  fullScorecard: {
    innings: [
      {
        id: 2,
        isDeclared: false,
        name: "1st Inn Rajasthan Royals ",
        shortName: "1st RAJ",
        team: {
          id: 64,
          shortName: "RAJ",
        },
        batsmen: [
          {
            id: 3845,
            name: "Ajinkya Rahane",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Test-2021/Ajinkya-Rahane-Test2021.ashx",
            runs: "14",
            balls: "17",
            strikeRate: "82.35",
            fours: "1",
            sixes: "0",
            howOut: "c: Pandya b: McClenaghan",
            fallOfWicket: "2-38",
            fallOfWicketOver: "5.4",
            fowOrder: 2,
          },
          {
            id: 11108,
            name: "Rahul Tripathi",
            runs: "9",
            balls: "8",
            strikeRate: "112.50",
            fours: "1",
            sixes: "0",
            howOut: "c: Yadav b: Pandya",
            fallOfWicket: "1-14",
            fallOfWicketOver: "2.2",
            fowOrder: 1,
          },
          {
            id: 5335,
            name: "Sanju Samson",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Sanju-Samson-T20I2020.ashx",
            runs: "52",
            balls: "39",
            strikeRate: "133.33",
            fours: "4",
            sixes: "0",
            howOut: "c: Pandya b: Bumrah",
            fallOfWicket: "4-125",
            fallOfWicketOver: "16.2",
            fowOrder: 4,
          },
          {
            id: 4489,
            name: "Ben Stokes",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/England/Ben-Stokes-CWC19.ashx",
            runs: "40",
            balls: "27",
            strikeRate: "148.15",
            fours: "3",
            sixes: "1",
            howOut: "b: Pandya",
            fallOfWicket: "3-110",
            fallOfWicketOver: "14.1",
            fowOrder: 3,
          },
          {
            id: 4456,
            name: "Jos Buttler",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Sydney%20Thunder/BBL08/Jos_Buttler_BBL08.ashx",
            runs: "6",
            balls: "8",
            strikeRate: "75.00",
            fours: "0",
            sixes: "0",
            howOut: "b: Bumrah",
            fallOfWicket: "5-125",
            fallOfWicketOver: "16.3",
            fowOrder: 5,
          },
          {
            id: 7620,
            name: "Heinrich Klaasen",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/South%20Africa/Heinrich-Klaasen-ODI18.ashx",
            runs: "0",
            balls: "1",
            strikeRate: "0.00",
            fours: "0",
            sixes: "0",
            howOut: "c: Kishan b: Rahman",
            fallOfWicket: "6-125",
            fallOfWicketOver: "17.1",
            fowOrder: 6,
          },
          {
            id: 9855,
            name: "Jofra Archer",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Hobart%20Hurricanes/BBL08/Joffra_Archer_BBL08.ashx",
            runs: "8",
            balls: "9",
            strikeRate: "88.89",
            fours: "1",
            sixes: "0",
            howOut: "c&b: Pandya",
            fallOfWicket: "7-158",
            fallOfWicketOver: "19.1",
            fowOrder: 7,
          },
          {
            id: 11095,
            name: "Krishnappa Gowtham",
            runs: "33",
            balls: "11",
            strikeRate: "300.00",
            fours: "4",
            sixes: "2",
            howOut: "not out",
            fowOrder: 0,
          },
          {
            id: 4768,
            name: "Jaydev Unadkat",
            runs: "0",
            balls: "0",
            strikeRate: "0",
            fours: "0",
            sixes: "0",
            howOut: "not out",
            fowOrder: 0,
          },
          {
            id: 3842,
            name: "Dhawal Kulkarni",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/dhawal-kulkarni-ind.ashx",
            runs: "",
            balls: "",
            strikeRate: "-",
            fours: "",
            sixes: "",
            howOut: "",
            fowOrder: 0,
          },
          {
            id: 7338,
            name: "Shreyas Gopal",
            runs: "",
            balls: "",
            strikeRate: "-",
            fours: "",
            sixes: "",
            howOut: "",
            fowOrder: 0,
          },
        ],
        bowlers: [
          {
            id: 4872,
            name: "Mitchell McClenaghan",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Sydney%20Thunder/BBL07/Mitchell-McClenaghan-BBL07.ashx",
            runsConceded: "32",
            maidens: "0",
            wickets: "1",
            overs: "3.0",
            wides: "1",
            noBalls: "0",
            economy: "10.67",
          },
          {
            id: 6684,
            name: "Jasprit Bumrah",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Test-2021/Jasprit-Bumrah-Test2021.ashx",
            runsConceded: "28",
            maidens: "0",
            wickets: "2",
            overs: "4.0",
            wides: "0",
            noBalls: "1",
            economy: "7.00",
          },
          {
            id: 9686,
            name: "Krunal Pandya",
            runsConceded: "33",
            maidens: "0",
            wickets: "1",
            overs: "4.0",
            wides: "2",
            noBalls: "0",
            economy: "8.25",
          },
          {
            id: 6752,
            name: "Mustafizur Rahman",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/Bangladesh/Mustafizur-Rahman-CWC19.ashx",
            runsConceded: "35",
            maidens: "0",
            wickets: "1",
            overs: "4.0",
            wides: "0",
            noBalls: "1",
            economy: "8.75",
          },
          {
            id: 11075,
            name: "Mayank Markande",
            runsConceded: "15",
            maidens: "0",
            wickets: "0",
            overs: "2.0",
            wides: "0",
            noBalls: "0",
            economy: "7.50",
          },
          {
            id: 7780,
            name: "Hardik Pandya",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Hardik-Pandya-T20I2020.ashx",
            runsConceded: "25",
            maidens: "0",
            wickets: "2",
            overs: "2.4",
            wides: "1",
            noBalls: "0",
            economy: "9.38",
          },
        ],
        wicket: "7",
        run: "168",
        over: "19.4",
        extra: "6",
        bye: "0",
        legBye: "0",
        wide: "4",
        noBall: "2",
        runRate: "8.54",
        requiredRunRate: "0.00",
      },
      {
        id: 1,
        isDeclared: false,
        name: "1st Inn Mumbai Indians ",
        shortName: "1st MI",
        team: {
          id: 62,
          shortName: "MI",
        },
        batsmen: [
          {
            id: 5089,
            name: "Suryakumar Yadav",
            runs: "72",
            balls: "47",
            strikeRate: "153.19",
            fours: "6",
            sixes: "3",
            howOut: "c: Buttler b: Unadkat",
            fallOfWicket: "3-135",
            fallOfWicketOver: "15.2",
            fowOrder: 3,
          },
          {
            id: 5904,
            name: "Evin Lewis",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/West%20Indies/ODIWC19/Evin-Lewis-CWC19.ashx",
            runs: "0",
            balls: "1",
            strikeRate: "0.00",
            fours: "0",
            sixes: "0",
            howOut: "b: Kulkarni",
            fallOfWicket: "1-1",
            fallOfWicketOver: "0.4",
            fowOrder: 1,
          },
          {
            id: 8234,
            name: "Ishan Kishan",
            runs: "58",
            balls: "42",
            strikeRate: "138.10",
            fours: "4",
            sixes: "3",
            howOut: "c: Buttler b: Kulkarni",
            fallOfWicket: "2-130",
            fallOfWicketOver: "14.2",
            fowOrder: 2,
          },
          {
            id: 3499,
            name: "Kieron Pollard",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Adelaide%20Strikers/Archive/Adelaide%20Stikers%20New/Kieron-Pollard.ashx",
            runs: "21",
            balls: "20",
            strikeRate: "105.00",
            fours: "1",
            sixes: "1",
            howOut: "not out",
            fowOrder: 0,
          },
          {
            id: 3516,
            name: "Rohit Sharma",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Rohit-Sharma-Test2021.ashx",
            runs: "0",
            balls: "1",
            strikeRate: "0.00",
            fours: "0",
            sixes: "0",
            howOut: "run out (Rahane)",
            fallOfWicket: "4-136",
            fallOfWicketOver: "15.4",
            fowOrder: 4,
          },
          {
            id: 9686,
            name: "Krunal Pandya",
            runs: "7",
            balls: "6",
            strikeRate: "116.67",
            fours: "1",
            sixes: "0",
            howOut: "c: Klaasen b: Archer",
            fallOfWicket: "5-153",
            fallOfWicketOver: "18.1",
            fowOrder: 5,
          },
          {
            id: 7780,
            name: "Hardik Pandya",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Hardik-Pandya-T20I2020.ashx",
            runs: "4",
            balls: "2",
            strikeRate: "200.00",
            fours: "1",
            sixes: "0",
            howOut: "b: Archer",
            fallOfWicket: "6-158",
            fallOfWicketOver: "18.4",
            fowOrder: 6,
          },
          {
            id: 4872,
            name: "Mitchell McClenaghan",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Sydney%20Thunder/BBL07/Mitchell-McClenaghan-BBL07.ashx",
            runs: "0",
            balls: "1",
            strikeRate: "0.00",
            fours: "0",
            sixes: "0",
            howOut: "b: Archer",
            fallOfWicket: "7-158",
            fallOfWicketOver: "18.5",
            fowOrder: 7,
          },
          {
            id: 11075,
            name: "Mayank Markande",
            runs: "0",
            balls: "1",
            strikeRate: "0.00",
            fours: "0",
            sixes: "0",
            howOut: "not out",
            fowOrder: 0,
          },
          {
            id: 6684,
            name: "Jasprit Bumrah",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/Test-2021/Jasprit-Bumrah-Test2021.ashx",
            runs: "",
            balls: "",
            strikeRate: "-",
            fours: "",
            sixes: "",
            howOut: "",
            fowOrder: 0,
          },
          {
            id: 6752,
            name: "Mustafizur Rahman",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/Bangladesh/Mustafizur-Rahman-CWC19.ashx",
            runs: "",
            balls: "",
            strikeRate: "-",
            fours: "",
            sixes: "",
            howOut: "",
            fowOrder: 0,
          },
        ],
        bowlers: [
          {
            id: 3842,
            name: "Dhawal Kulkarni",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/India/dhawal-kulkarni-ind.ashx",
            runsConceded: "32",
            maidens: "0",
            wickets: "2",
            overs: "4.0",
            wides: "2",
            noBalls: "0",
            economy: "8.00",
          },
          {
            id: 11095,
            name: "Krishnappa Gowtham",
            runsConceded: "20",
            maidens: "0",
            wickets: "0",
            overs: "3.0",
            wides: "0",
            noBalls: "0",
            economy: "6.67",
          },
          {
            id: 9855,
            name: "Jofra Archer",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/Domestic/Hobart%20Hurricanes/BBL08/Joffra_Archer_BBL08.ashx",
            runsConceded: "22",
            maidens: "0",
            wickets: "3",
            overs: "4.0",
            wides: "0",
            noBalls: "0",
            economy: "5.50",
          },
          {
            id: 4768,
            name: "Jaydev Unadkat",
            runsConceded: "31",
            maidens: "0",
            wickets: "1",
            overs: "4.0",
            wides: "0",
            noBalls: "0",
            economy: "7.75",
          },
          {
            id: 7338,
            name: "Shreyas Gopal",
            runsConceded: "30",
            maidens: "0",
            wickets: "0",
            overs: "2.0",
            wides: "1",
            noBalls: "0",
            economy: "15.00",
          },
          {
            id: 4489,
            name: "Ben Stokes",
            imageURL:
              "https://www.cricket.com.au/-/media/Players/Men/International/England/Ben-Stokes-CWC19.ashx",
            runsConceded: "31",
            maidens: "0",
            wickets: "0",
            overs: "3.0",
            wides: "0",
            noBalls: "1",
            economy: "10.33",
          },
        ],
        wicket: "7",
        run: "167",
        over: "20.0",
        extra: "5",
        bye: "0",
        legBye: "1",
        wide: "3",
        noBall: "1",
        runRate: "8.35",
        requiredRunRate: "",
      },
    ],
  },
  fullScorecardAwards: {
    mostRunsAward: {
      id: 5089,
      name: "Suryakumar Yadav",
      runs: "72",
      balls: "47",
      strikeRate: "153.19",
      fowOrder: 0,
    },
    mostWicketsAward: {
      id: 9855,
      name: "Jofra Archer",
      runsConceded: "22",
      wickets: "3",
      overs: "4.0",
      economy: "5.5",
    },
    manOfTheMatchId: 9855,
    manOfTheMatchName: "Jofra Archer",
    manOfMatchBattingResults: [
      {
        id: 9855,
        name: "Jofra Archer",
        runs: "8",
        balls: "9",
        strikeRate: "88.89",
        fours: "1",
        sixes: "0",
        howOut: "c&b: Pandya",
        fallOfWicket: "7-158",
        fallOfWicketOver: "19.1",
        fowOrder: 7,
      },
    ],
    manOfMatchBowlngResults: [
      {
        id: 9855,
        name: "Jofra Archer",
        runsConceded: "22",
        maidens: "0",
        wickets: "3",
        overs: "4.0",
        wides: "0",
        noBalls: "0",
        economy: "5.50",
      },
    ],
    mostRunsAwardPlayerResults: [
      {
        id: 5089,
        name: "Suryakumar Yadav",
        runs: "72",
        balls: "47",
        strikeRate: "153.19",
        fours: "6",
        sixes: "3",
        howOut: "c: Buttler b: Unadkat",
        fallOfWicket: "3-135",
        fallOfWicketOver: "15.2",
        fowOrder: 3,
      },
    ],
    mostWicketsAwardPlayerResults: [
      {
        id: 9855,
        name: "Jofra Archer",
        runsConceded: "22",
        maidens: "0",
        wickets: "3",
        overs: "4.0",
        wides: "0",
        noBalls: "0",
        economy: "5.50",
      },
    ],
  },
  status: 200,
  poweredBy: "dev132",
};
